set_property IOSTANDARD LVCMOS33 [get_ports {ctr_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ctr_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ctr_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ctr_out[0]}]
set_property PACKAGE_PIN V19 [get_ports {ctr_out[3]}]
set_property PACKAGE_PIN U19 [get_ports {ctr_out[2]}]
set_property PACKAGE_PIN E19 [get_ports {ctr_out[1]}]
set_property PACKAGE_PIN U16 [get_ports {ctr_out[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports count]
set_property IOSTANDARD LVCMOS33 [get_ports count]
set_property PACKAGE_PIN T17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

set_property SLEW SLOW [get_ports {ctr_out[3]}]
set_property SLEW SLOW [get_ports {ctr_out[2]}]
set_property SLEW SLOW [get_ports {ctr_out[1]}]
set_property SLEW SLOW [get_ports {ctr_out[0]}]
set_property DRIVE 12 [get_ports {ctr_out[3]}]
set_property DRIVE 12 [get_ports {ctr_out[2]}]
set_property DRIVE 12 [get_ports {ctr_out[1]}]
set_property DRIVE 12 [get_ports {ctr_out[0]}]
